# FROM python:3.10


# RUN pip3 install xgboost==1.5.1
# RUN pip3 install numpy
# RUN pip3 install influxdb-client

FROM jupyter/pyspark-notebook

COPY . .

RUN pip install \
    influxdb-client \
    numpy \
    pandas==1.5.3 \
    xgboost==1.5.1 \
    pyspark